### ISSUE TITLE
Failed to install grunt-contrib-handlebars

### ISSUE THREAD

**Issue by trantorLiu** [rendrjs/rendr-app-template#13]
I tried modifying the line `git://github.com/spikebrehm/grunt-contrib-handlebars#d61e7457c6551965f88de46ad207fd67d18ddd4a` in `package.json`  to `git://github.com/spikebrehm/grunt-contrib-handlebars`, but it didn't work.
Here's the npm log:

```
201 error Error: `git "clone" "--mirror" "git://github.com/spikebrehm/grunt-contrib-handlebars" "/home/chun-yi/.npm/_git-remotes/git-github-com-spikebrehm-grunt-contrib-handlebars-683221c7"` failed with 128
201 error     at ChildProcess.<anonymous> (/home/chun-yi/.nvm/v0.8.20/lib/node_modules/npm/lib/utils/exec.js:56:20)
201 error     at ChildProcess.EventEmitter.emit (events.js:99:17)
201 error     at maybeClose (child_process.js:638:16)
201 error     at Process._handle.onexit (child_process.js:680:5)
202 error If you need help, you may report this log at:
202 error     <http://github.com/isaacs/npm/issues>
202 error or email it to:
202 error     <npm-@googlegroups.com>
203 error System Linux 2.6.32-45-generic
204 error command "/home/chun-yi/.nvm/v0.8.20/bin/node" "/home/chun-yi/.nvm/v0.8.20/bin/npm" "install"
205 error cwd /home/chun-yi/rendr-app-template
206 error node -v v0.8.20
207 error npm -v 1.2.11
208 verbose exit [ 1, true ]
```

And my grunt version:

```
grunt-cli v0.1.7
grunt v0.4.1
```

**Comment by spikebrehm** [comment]
You get it to work @trantorLiu?

**Comment by trantorLiu** [comment]
Yes. I don't know why everything installed smoothly after I went home. I changed nothing.
