### ISSUE TITLE
Error when hitting reload on sub-pages (repos or users)

### ISSUE THREAD

**Issue by hjortureh** [rendrjs/rendr-app-template#3]
Hello,

I was able to get the rendr-app-template app up and running and everything works as expected until I hit the refresh button in the browser on the repos or users sub-pages.  

Not sure if I'm the only one having this problem but decided to post the error anyways:

Express
500 TypeError: Cannot call method 'makeRequest' of null

```
at serverSync [as sync] (/Users/myuser/node/rendr-app-template/node_modules/rendr/shared/syncer.coffee:51:31)
at _.extend.fetch (/Users/myuser/node/rendr-app-template/node_modules/rendr/node_modules/backbone/backbone.js:860:19)
at module.exports.Base.fetch (/Users/myuser/node/rendr-app-template/node_modules/rendr/shared/base/collection.coffee:67:35)
at fetchFromApi (/Users/myuser/node/rendr-app-template/node_modules/rendr/shared/fetcher.coffee:146:18)
at Object._.each.batchedRequests.(anonymous function) [as collection] (/Users/myuser/node/rendr-app-template/node_modules/rendr/shared/fetcher.coffee:92:18)
at async.parallel (/Users/myuser/node/rendr-app-template/node_modules/rendr/node_modules/async/lib/async.js:467:25)
at async.forEach (/Users/myuser/node/rendr-app-template/node_modules/rendr/node_modules/async/lib/async.js:86:13)
at Array.forEach (native)
at _forEach (/Users/myuser/node/rendr-app-template/node_modules/rendr/node_modules/async/lib/async.js:26:24)
at Object.async.forEach (/Users/myuser/node/rendr-app-template/node_modules/rendr/node_modules/async/lib/async.js:85:9)
at Object.async.parallel (/Users/myuser/node/rendr-app-template/node_modules/rendr/node_modules/async/lib/async.js:466:19)
at retrieve (/Users/myuser/node/rendr-app-template/node_modules/rendr/shared/fetcher.coffee:121:18)
at Object.fetcher.fetch (/Users/myuser/node/rendr-app-template/node_modules/rendr/shared/fetcher.coffee:268:12)
at module.exports.App.fetch (/Users/myuser/node/rendr-app-template/node_modules/rendr/shared/app.coffee:40:27)
at Object.module.exports.index (/Users/myuser/node/rendr-app-template/app/controllers/repos_controller.js:6:14)
at module.exports.ServerRouter.getHandler (/Users/myuser/Node/rendr-app-template/node_modules/rendr/server/router.coffee:50:23)
at callbacks (/Users/myuser/Node/rendr-app-template/node_modules/express/lib/router/index.js:161:37)
at module.exports (/Users/myuser/Node/rendr-app-template/node_modules/rendr/server/middleware/initApp.coffee:12:14)
at callbacks (/Users/myuser/Node/rendr-app-template/node_modules/express/lib/router/index.js:161:37)
at param (/Users/myuser/Node/rendr-app-template/node_modules/express/lib/router/index.js:135:11)
at pass (/Users/myuser/Node/rendr-app-template/node_modules/express/lib/router/index.js:142:5)
at Router._dispatch (/Users/myuser/Node/rendr-app-template/node_modules/express/lib/router/index.js:170:5)
at Object.router (/Users/myuser/Node/rendr-app-template/node_modules/express/lib/router/index.js:33:10)
at next (/Users/myuser/Node/rendr-app-template/node_modules/express/node_modules/connect/lib/proto.js:190:15)
at multipart (/Users/myuser/Node/rendr-app-template/node_modules/express/node_modules/connect/lib/middleware/multipart.js:64:37)
at module.exports (/Users/myuser/Node/rendr-app-template/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:57:9)
at urlencoded (/Users/myuser/Node/rendr-app-template/node_modules/express/node_modules/connect/lib/middleware/urlencoded.js:51:37)
at module.exports (/Users/myuser/Node/rendr-app-template/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:55:7)
at json (/Users/myuser/Node/rendr-app-template/node_modules/express/node_modules/connect/lib/middleware/json.js:53:37)
at Object.bodyParser [as handle] (/Users/myuser/Node/rendr-app-template/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:53:5)
at next (/Users/myuser/Node/rendr-app-template/node_modules/express/node_modules/connect/lib/proto.js:190:15)
at Object.logger (/Users/myuser/Node/rendr-app-template/node_modules/express/node_modules/connect/lib/middleware/logger.js:156:5)
at next (/Users/myuser/Node/rendr-app-template/node_modules/express/node_modules/connect/lib/proto.js:190:15)
at resume (/Users/myuser/Node/rendr-app-template/node_modules/express/node_modules/connect/lib/middleware/static.js:60:7)
at SendStream.error (/Users/myuser/Node/rendr-app-template/node_modules/express/node_modules/connect/lib/middleware/static.js:73:37)
at SendStream.EventEmitter.emit (events.js:115:20)
at SendStream.error (/Users/myuser/Node/rendr-app-template/node_modules/express/node_modules/send/lib/send.js:147:51)
at SendStream.onStatError (/Users/myuser/Node/rendr-app-template/node_modules/express/node_modules/send/lib/send.js:248:48)
at SendStream.pipe (/Users/myuser/Node/rendr-app-template/node_modules/express/node_modules/send/lib/send.js:320:26)
at Object.oncomplete (fs.js:297:15) 
```

QUICK NOTE:  Also had to have coffee-script & grunt pre-installed globally with -g to be able to run the app,  maybe worth mentioning under "running the example" in the readme.

**Comment by spikebrehm** [comment]
Strange - why would `dataAdapter` be null?  I'll have to look into that one; I don't see that happening locally.

Good point re: coffe-script and grunt!
