### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by mattpardee** [rendrjs/rendr-app-template#48]
Getting a `Cannot read property 'handle' of undefined` when starting. Not sure what's going on.

```
Running "runNode" task

Running "handlebars:compile" (handlebars) task
26 Sep 21:16:40 - [nodemon] v0.7.10
26 Sep 21:16:40 - [nodemon] to restart at any time, enter `rs`
26 Sep 21:16:40 - [nodemon] watching: /root/rendr-app-template
26 Sep 21:16:40 - [nodemon] starting `node --debug index.js`
File "app/templates/compiledTemplates.js" created.

Running "rendr_stitch:compile" (rendr_stitch) task
debugger listening on port 5858
26 Sep 21:16:40 - [nodemon] reading ignore list
File "public/mergedAssets.js" created.

Running "stylus:compile" (stylus) task

/root/rendr-app-template/node_modules/express/lib/application.js:113
  if (fn.handle && fn.set) app = fn;
        ^
TypeError: Cannot read property 'handle' of undefined
    at Function.app.use (/root/rendr-app-template/node_modules/express/lib/application.js:113:9)
    at initMiddleware (/root/rendr-app-template/index.js:27:7)
    at Object.<anonymous> (/root/rendr-app-template/index.js:68:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3
```

**Comment by spikebrehm** [comment]
Doh, this is due to some changes I just pushed to master (bleeding edge).  Let me investigate now.

You can use the latest stable version, which is 0.4.10.

**Comment by spikebrehm** [comment]
fixed in https://github.com/airbnb/rendr-app-template/pull/49

**Comment by sahil-verma** [comment]
what should be the solution for this error
